# dev – Activated when in development mode (i.e. mvn quarkus:dev)
"%dev":
  message: hello
  environment:
    name: local
  quarkus:
    kubernetes-config:
      enabled: false
# test – Activated when running tests (i.e. mvn test)
"%test":
  message: hello
  environment:
    name: local
  quarkus:
    kubernetes-config:
      enabled: false
# prod – The default profile when not running in development or test mode
"%prod":
  quarkus:
    kubernetes-config:
      enabled: true
      # next, lsit of configmaps to be used by the app
      # from top to bottom, less to high priority
      config-maps:
        - quarkus-hello-world
        - env-ops-quarkus-hello-world
        - global-ops-quarkus-hello-world
